spring.jpa:
  show-sql: true
  properties:
    hibernate.format_sql: true

security:
  ignored: /**, /swagger-ui.html, /swagger-resources/**, /v2/api-docs/**, /configuration/**, /webjars/**, /raml/**, /console/**
  user:
    name: demo
    password: omed.1

logging:
  level:
    root: INFO
    com.az.ip.api: DEBUG
    # Set DEBUG level to activate our log-filter to log each request and response
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    # Set TTRACE to see actual parameter and result set values
    org.hibernate.type: TRACE

#server:
#  ssl:
#    key-store: classpath:server.jks
#    key-store-password: password
#    key-password: password

---
# For deployment in Docker containers
spring:
  profiles: docker

#server:
#  ssl:
#    key-store: server.jks

