      description: Collection of available <<resourcePathName>>.
      get:
        description: Get a list of <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName|!pluralize>>
                example: |
                  <<exampleCollection>>
          422:
            description: |
              Invalid parameters in request, see error message in body for more information
            body:
              application/json:
                schema: error
                example: |
                  {
                    "code": 999,
                    "message": "...error message explaning the reason for returning an error..."
                  }
      post:
        description: |
          Add a new <<resourcePathName|!singularize>>.
        queryParameters:
          access_token:
            description: "The access token provided by the authentication application"
            example: AABBCCDD
            required: true
            type: string
        body:
          application/json:
            schema: <<resourcePathName|!singularize>>
            example: |
              <<exampleNewItem>>
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName|!singularize>>
                example: |
                  <<exampleItem>>
          409:
            description: |
              Duplicate error, see error message in body for more information
            body:
              application/json:
                schema: error
                example: |
                  {
                    "code": 999,
                    "message": "...error message explaning the reason for returning an error..."
                  }
