      description: Entity representing a <<resourcePathName|!singularize>>
      get:
        description: |
          Get the <<resourcePathName|!singularize>>
          with <<resourcePathName|!singularize>>Id =
          {<<resourcePathName|!singularize>>Id}

        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName|!singularize>>
                example: |
                  <<exampleItem>>

          404:
            description: |
              The entity was not found

      put:
        description: |
          Updates an existing <<resourcePathName|!singularize>>.
        queryParameters:
          access_token:
            description: "The access token provided by the authentication application"
            example: AABBCCDD
            required: true
            type: string
        body:
          application/json:
            schema: <<resourcePathName|!singularize>>
            example: |
              <<exampleItem>>

        responses:
          200:
#            body:
#              application/json:
#                example: |
#                  { "message": "The <<resourcePathName|!singularize>> has been properly entered" }

          422:
            description: |
              Invalid parameters in request, see error message in body for more information
            body:
              application/json:
                schema: error
                example: |
                  {
                    "code": 999,
                    "message": "...error message explaning the reason for returning an error..."
                  }
      delete:
        description: |
          Deletes an existing <<resourcePathName|!singularize>>.
        queryParameters:
          access_token:
            description: "The access token provided by the authentication application"
            example: AABBCCDD
            required: true
            type: string
        body:

        responses:
          200:
          422:
            description: |
              Invalid parameters in request, see error message in body for more information
            body:
              application/json:
                schema: error
                example: |
                  {
                    "code": 999,
                    "message": "...error message explaning the reason for returning an error..."
                  }
