      description: Collection of available <<resourcePathName>>.
      get:
        description: Get a list of <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName|!pluralize>>
                example: |
                  <<exampleCollection>>
          # Invalid parameters in request
          422:
            body:
              application/json:
                schema: error
      post:
        description: |
          Add a new <<resourcePathName|!singularize>>.
        queryParameters:
          access_token:
            description: "The access token provided by the authentication application"
            example: AABBCCDD
            required: true
            type: string
        body:
          application/json:
            schema: <<resourcePathName|!singularize>>
            example: |
              <<exampleItem>>
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName|!singularize>>
                example: |
                  <<exampleItem>>
          # Duplicate error
          409:
            body:
              application/json:
                schema: error
