#%RAML 0.8
title: AZ IP API
version: v0.2
#baseUri: /api
baseUri: https://localhost:8080/api
securitySchemes:
  - basic:
      type: Basic Authentication
securedBy: [basic]

schemas:
  - study:    !include study/study.schema
  - studies:  !include study/studies.schema
  - patient:  !include patient/patient.schema
  - patients: !include patient/patients.schema
  - error:    !include common/error.schema

resourceTypes:
  - readOnlyCollection: !include common/resourceTypes/readOnlyCollection.raml
  - collection:         !include common/resourceTypes/collection.raml
  - collectionItem:     !include common/resourceTypes/collectionItem.raml

traits:
  - searchable: !include common/traits/searchable.raml
  - orderable:  !include common/traits/orderable.raml
  - pageable:   !include common/traits/pageable.raml

/coutries:

/studies:
  type:
    collection:
      exampleCollection: !include study/studies.sample
      exampleItem: !include study/study-new.sample
  get:
    is: [
          orderable: {fieldsList: "name"},
          pageable
        ]
    queryParameters:
      name:
        description: "Search by name"
        example: study-1
        required: false
        type: string
  /{id}:
    type:
      collectionItem:
        exampleItem: !include study/study-retrieve.sample

/applications:
/sensors:

/patients:
  type:
    collection:
      exampleCollection: !include patient/patients.sample
      exampleItem: !include patient/patient-new.sample
  get:
    is: [
          searchable: {description: "with valid searchable fields: lastName", example: "[\"lastName\", \"l\", \"matches\"]"},
          orderable: {fieldsList: "username, firstName, lastName"},
          pageable
        ]
  /{username}:
    type:
      collectionItem:
        exampleItem: !include patient/patient-retrieve.sample

/carers:
  post:
    body:
      application/json:
        example: | 
          {
            "username": "u1",
            "patientID": "1",
            "firstname": "f1",
            "lastname": "l1",
            "weight": "100",
            "height": "200"
          }
    responses:
      200:
      500:
        body:
          application/json:
            example: |
              {
                "errorMessage": "The patient couldn't be created."
              }
  get:
    responses:
      200:
        body:
          application/json:
            example: | 
              [
                {
                  "username": "u1",
                  "patientID": "1",
                  "firstname": "f1",
                  "lastname": "l1",
                  "weight": "101",
                  "height": "201"
                },
                {
                  "username": "u2",
                  "patientID": "2",
                  "firstname": "f2",
                  "lastname": "l2",
                  "weight": "102",
                  "height": "202"
                }
              ]
/doctors:
